apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: test
  labels:
    app: busybox
spec:
    containers:
      - name: busybox
        image: busybox
        # options Always|IfNotPresent|Never
        imagePullPolicy: IfNotPresent
        env:
          - name: app
            value: busybox
        # 运行终端
        tty: true
        # 特权模型 对宿主机有root权限
        securityContext:
          privileged: true
        workingDir: /test
        # 命令
        command: ["/bin/sh"]
        # 参数
        args: ["-c,"while true;do echo hello;sleep 10;done"]
        resources:
          requests:
            memory: "100Mi"
            cpu: "1000m"
          limits:
            memory: "200Mi"
            cpu: "1000m"
