apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: test
  labels:
    app: nginx
spec:
  # 是不是使用主机上的网络，而不是虚拟 的虚拟网路
  hostNetwork: true
  # options Default|CusterFirst|ClusterFirstWithHostNet|None
  dnsPolicy: "Default"
  dnsConfig:
    nameservers:
      - 8.8.8.8
  hostAliases:
    - ip: 192.168.1.18
      hostnames:
        - "fool.local"
        - "bar.local"
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - name: default
          containerPort: 80
          # 如果使用 hostNetwork 就不能指定端口
          hostPort: 8080